### ISSUE TITLE
generator.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [VolodymyrVoloshyn/Angular2Shop#12]
@Injectable() +  constructor(private length: number)
В случае продакшин билда будет сообщение-предупреждение
Can't resolve all parameters for GeneratorService in D:/GitRepo/Home/Volodymyr_Voloshyn/src/app/services/generator.service.ts: (?). This will become an error in Angular v6.x
Это сообщение говорит о том, что если есть декоратор @Injectable(), то параметры конструктора воспринимаются как зависимости (сервисы). Можно либо убрать декоратор, либо не использовать конструктор для задания параметра length

**Comment by VolodymyrVoloshyn** [comment]
Исправил.
