### ISSUE TITLE
app.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [VolodymyrVoloshyn/Angular2Shop#3]
Почему бы не сделать метод 
getCartItemsCount(): number {
    return this.cartService.getProductsCount();
  }
методом isCartVisible(): boolean {
    return this.cartService.getProductsCount() > 0;
}
и избавиться от выражения сравнения в шаблоне.

**Comment by VolodymyrVoloshyn** [comment]
Согласен. Исправил
