### ISSUE TITLE
product.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [VolodymyrVoloshyn/Angular2Shop#5]
Не понял зачем такое большое количество гетеров в классе?

**Comment by VolodymyrVoloshyn** [comment]
Первое и главное зачем,  это то что product мог быть null,(проблема связанная с моим "вопросом 2" https://github.com/VolodymyrVoloshyn/Angular2Shop/issues/8), в гетерах я делал проверку, чтобы не было ошибки. Сейчас это переделано и не актуально.

Второе. Скрыть доступ к самому объекту product и дать доступ только к его свойствам, которые должны быть отображены. Это излишне?

**Comment by VZhyrytskiy** [comment]
Тяжело читается.
