### ISSUE TITLE
Ответ на вопрос 1

### ISSUE THREAD

**Issue by VZhyrytskiy** [VolodymyrVoloshyn/Angular2Shop#7]
Вопрос который уже задавал (ниже). Я так и не понял как без переменной получить доступ к елементу шаблона компоненты. 
Пробывал передать ElementRef в конструктор компонента и через него и querySelector получить доступ к элементу, но так тоже не работает. Элемента просто еще нету а момент клика.
А если с переменной и ngAfterViewInit, то тоже не понял как. ngAfterViewInit отрабатывает один раз при создание компонента, а мне нужен доступ во время жизни.

Не нужно получать доступ к этой переменной. Добавьте атрибут autofocus
<input *ngIf="isSelected; else elseBlock" autofocus type="number" min="1" [(ngModel)]="cartItem.quantity" class="ciQnt" (blur)="editFinished()" >

**Comment by VolodymyrVoloshyn** [comment]
Переделал (сейчас залито), но фокус устанавливается только в первый раз, в последуюющие клики переводят элемент в редактирование, но фокус в инпут не устанавливается.

**Comment by VZhyrytskiy** [comment]
Вы правы. У меня получился вариант без переменной inputCartItemQnt, но с setTimeout. Element, который вы передаете в конструктор это хост элемент. Можно в нем поискать инпут. Избавиться от setTimeout пока не получилось. Может быть попробовать использовать не *ngIf, а атрибут [hidden]. Не пробовал.
