### ISSUE TITLE
Ответ на вопрос 2

### ISSUE THREAD

**Issue by VZhyrytskiy** [VolodymyrVoloshyn/Angular2Shop#8]
Вторая похожая проблема. Если компонент список продуктов (ProductListComponent) и компонент информация по продукту (ProductComponent). При клике на каком-то продукте в ProductListComponent, продукт передается через свойство комоненту ProductComponent для отобращение деталей. Хотелось при загрузке приложения ProductComponent скрыть, потому как никакой продукт не выбран и отображать там нечего, но ngIf тут не помогает потому как при первом клике ProductComponent не существует и присвоение его свойтву продукта вызывает ошибку. 

Необходимо реализовать следующее:
Когда пользователь выбирает товар, то выполняется метод 
onSelect(product: IProduct): void {
   // показать детали
    this.showProductDetatil = true;
   // фиксируем товар для показа
    this.product = product;
    // this.productDetail.product = product;
  }
Дополнительно необходимо объявить своство product: any | IProduct; (с вашим типом) 

В разметке делаем следующее
<app-product *ngIf="showProductDetatil"  
[product]="product" 
(add)="onProductAdd($event)"></app-product>

**Comment by VolodymyrVoloshyn** [comment]
Переделал заработало.
Я хотел обойтись без фиксации товара на компоненте родителя. Зачем родителю хранить эту информацию. Я и пытался сделать тоже самое, без хранения выбранного товара в родительском компоненте. 
Это также будет усложнять разработку и поддержку, подобные сыылки нужно поддерживать в актуальном состоянии, в зависимости от состояния компонентов (в реальном более сложном приложении). Думаю, особенно актуально это будет при обработке ошибок, исключительных ситуаций.
